version: '3.8'

services:
  postgres:
    container_name: postgresql-personal
    image: postgres:16
    ports:
      - '5532:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - docker-postgres-db.env

volumes:
  db:
